### ISSUE TITLE
Add updated HSC constraints from arxiv.org/abs/1910.01285

### ISSUE THREAD

**Issue by bradkav** [bradkav/PBHbounds#1]

**Comment by MohsenQazi** [comment]
dear @bradkav,
I'm looking for a PhD and want to gain more experiences on ML and data analysis.
So, I find your repos and this issue.
Did you contact with the authors of arXiv:1910.01285 for their new bounds?
If no, would you mind if I have a try?

**Comment by bradkav** [comment]
Hi @MohsenQazi, 
Thanks for the interest! No I haven't added the updated constraint yet. If you want to contribute, feel free to contact the authors and ask for the results (or alternatively, digitise the curves from the plot in the paper).

**Comment by MohsenQazi** [comment]
@bradkav 
I've digitised the data from (https://github.com/MohsenQazi/PBHbounds/blob/master/bounds/HSC_enhanced.png), but the ones related to 1701.02151 don't match with (https://github.com/bradkav/PBHbounds/blob/master/bounds/HSC.txt).
Actually, plotting HSC.txt don't give the 1701.02151 plot.
Did I miss some steps?

**Comment by bradkav** [comment]
Hi @MohsenQazi I'm not sure what you mean. When I run the plotting script, I get this plot https://github.com/bradkav/PBHbounds/blob/master/plots/PBH_bounds.png, which shows the correct HSC bounds from 1701.02151 I think. What exactly is the problem? What do you expect it to look like, and how does it look instead?

Have you accounted for the fact that there are two mass axes (g and M_sun)?

**Comment by bradkav** [comment]
Hi @MohsenQazi, have you made any progress with this? Do you have the digitized bounds from 1910.01285? 

No stress if not, but I'm going through and updating a lot of the bounds now.
