### ISSUE TITLE
New quasar microlensing constraints

### ISSUE THREAD

**Issue by amgreennott** [bradkav/PBHbounds#13]
extending to smaller masses https://arxiv.org/abs/2307.07473

**Comment by bradkav** [comment]
I've added it as a new bounds file [Quasars-Xray.txt](https://github.com/bradkav/PBHbounds/blob/master/bounds/Quasars-Xray.txt). I've also updated the [Microlensing summary plot](https://github.com/bradkav/PBHbounds/blob/master/plots/PBHbounds_microlensing_square.pdf) to include the new version of the bound.

Thanks for pointing out this constraint (feel free to point out more in future!)
