### ISSUE TITLE
New limits on planetary mass PBHs from OGLE high cadence survey

### ISSUE THREAD

**Issue by amgreennott** [bradkav/PBHbounds#15]
New (tighter than existing) limits on planetary mass PBHs from OGLE high cadence survey https://arxiv.org/abs/2410.06251

Digitised limits available from
https://www.astrouw.edu.pl/ogle/ogle4/LMC_FFP_PBH/limits.txt

**Comment by bradkav** [comment]
Thanks for the links! I've added the new bound "OGLE-highcadence" - see the updated summary plot [here](https://github.com/bradkav/PBHbounds/blob/master/plots/PBHbounds_microlensing_square.pdf).
